### ISSUE TITLE
npm start failed

### ISSUE THREAD

**Issue by umpirsky** [antirek/hugu#5]
Failed to start on Ubuntu 14.04.3 LTS.

```
$ npm start

> HuGu@0.0.2 start /home/umpirsky/Projects/hugu
> node app.js

   info  - socket.io started

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1020:19)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at Function.app.listen (/home/umpirsky/Projects/hugu/node_modules/express/lib/application.js:534:24)
    at Object.<anonymous> (/home/umpirsky/Projects/hugu/app.js:38:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.25
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! HuGu@0.0.2 start: `node app.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the HuGu@0.0.2 start script 'node app.js'.
npm ERR! This is most likely a problem with the HuGu package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls HuGu
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/umpirsky/Projects/hugu/npm-debug.log
```

$ cat npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.2
3 info using node@v0.10.25
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart HuGu@0.0.2
7 info start HuGu@0.0.2
8 verbose unsafe-perm in lifecycle true
9 info HuGu@0.0.2 Failed to exec start script
10 verbose stack Error: HuGu@0.0.2 start: `node app.js`
10 verbose stack Exit status 8
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:743:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
11 verbose pkgid HuGu@0.0.2
12 verbose cwd /home/umpirsky/Projects/hugu
13 error Linux 3.13.0-63-generic
14 error argv "node" "/usr/local/bin/npm" "start"
15 error node v0.10.25
16 error npm  v2.11.2
17 error code ELIFECYCLE
18 error HuGu@0.0.2 start: `node app.js`
18 error Exit status 8
19 error Failed at the HuGu@0.0.2 start script 'node app.js'.
19 error This is most likely a problem with the HuGu package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node app.js
19 error You can get their info via:
19 error     npm owner ls HuGu
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by antirek** [comment]
hugu use port 80 for http access. Check port 80 or change it here https://github.com/antirek/hugu/blob/master/app.js#L17

**Comment by umpirsky** [comment]
@antirek OK, started with port 8888, what url should I visit now? Thanks.
